package com.arxyt.dominionsword.mtr.client;

import com.arxyt.dominionsword.client.ClientConfig;
import com.arxyt.dominionsword.mtr.DominionSwordMtrCompatMod;
import com.arxyt.dominionsword.mtr.bridge.MtrTrainCollisionGeometry;
import com.arxyt.dominionsword.mtr.network.MtrCompatNetwork;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.LevelRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.RenderLevelStageEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.mtr.core.data.VehicleCar;
import org.mtr.core.tool.Vector;
import org.mtr.mod.client.MinecraftClientData;

import java.util.ArrayList;
import java.util.List;

/** Client-only world wireframes generated by the exact same local shell builder as server collision. */
@Mod.EventBusSubscriber(modid = DominionSwordMtrCompatMod.MOD_ID, value = Dist.CLIENT)
public final class MtrTrainCollisionDebugRenderer {
    private static final double RENDER_RADIUS_SQR = 320D * 320D;

    private MtrTrainCollisionDebugRenderer() {}

    @SubscribeEvent
    public static void render(RenderLevelStageEvent event) {
        if (event.getStage() != RenderLevelStageEvent.Stage.AFTER_TRANSLUCENT_BLOCKS
                || !ClientConfig.MTR_TRAIN_COLLISION_DEBUG.get()) return;
        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.level == null || minecraft.player == null) return;
        Vec3 camera = event.getCamera().getPosition();
        PoseStack pose = event.getPoseStack();
        MultiBufferSource.BufferSource buffers = minecraft.renderBuffers().bufferSource();
        VertexConsumer lines = buffers.getBuffer(RenderType.lines());

        MinecraftClientData.getInstance().vehicles.forEach(vehicle -> {
            int[] carIndex = {0};
            vehicle.getVehicleCarsAndPositions().forEach(carAndBogies -> {
                int index = carIndex[0]++;
                VehicleCar car = carAndBogies.left();
                List<Vector> centers = new ArrayList<>();
                carAndBogies.right().forEach(pair -> centers.add(Vector.getAverage(pair.left(), pair.right())));
                if (centers.isEmpty()) return;
                Vector first = centers.get(0), last = centers.get(centers.size() - 1);
                double x = centers.stream().mapToDouble(point -> point.x).average().orElse(first.x);
                double y = centers.stream().mapToDouble(point -> point.y).average().orElse(first.y);
                double z = centers.stream().mapToDouble(point -> point.z).average().orElse(first.z);
                if (camera.distanceToSqr(x, y, z) > RENDER_RADIUS_SQR) return;
                double deltaX = last.x - first.x, deltaY = last.y - first.y, deltaZ = last.z - first.z;
                double yaw = Math.atan2(deltaX, deltaZ);
                double pitch = Math.atan2(deltaY, Math.hypot(deltaX, deltaZ));
                List<MtrCompatNetwork.DoorGeometryPacket.DoorBox> doorBoxes = MtrDoorGeometryClient.doors(vehicle.getId(), index);
                List<MtrCompatNetwork.DoorGeometryPacket.DoorBox> openDoorBoxes = vehicle.vehicleExtraData.getDoorMultiplier() > 0
                        ? doorBoxes : MtrDoorGeometryClient.heldDoors(vehicle.vehicleExtraData, index, doorBoxes);
                List<MtrTrainCollisionGeometry.DoorOpening> openings = openDoorBoxes.stream().map(door ->
                        new MtrTrainCollisionGeometry.DoorOpening((door.minX() + door.maxX()) * .5D < 0 ? -1 : 1,
                                Math.min(door.minZ(), door.maxZ()), Math.max(door.minZ(), door.maxZ()))).toList();

                pose.pushPose();
                pose.translate(x - camera.x, y - camera.y, z - camera.z);
                pose.mulPose(Axis.YP.rotation((float) yaw));
                pose.mulPose(Axis.XP.rotation((float) -pitch));
                for (AABB box : MtrTrainCollisionGeometry.shell(car.getWidth(), car.getLength(),
                        vehicle.vehicleExtraData.getDoorMultiplier() > 0 || !openings.isEmpty(), openings)) {
                    boolean body = box.maxY <= 0.73D || box.minY >= 3.19D;
                    LevelRenderer.renderLineBox(pose, lines, box, body ? 1F : .1F, body ? .55F : .9F,
                            body ? .08F : 1F, .9F);
                }
                for (MtrCompatNetwork.DoorGeometryPacket.DoorBox door : doorBoxes) {
                    AABB doorway = new AABB(Math.min(door.minX(), door.maxX()), Math.min(door.minY(), door.maxY()) - .03D,
                            Math.min(door.minZ(), door.maxZ()), Math.max(door.minX(), door.maxX()),
                            Math.max(door.minY(), door.maxY()) + .03D, Math.max(door.minZ(), door.maxZ()));
                    LevelRenderer.renderLineBox(pose, lines, doorway, .2F, 1F, .2F, 1F);
                }
                pose.popPose();
            });
        });
        buffers.endBatch(RenderType.lines());
    }
}
